# Generated by Django 4.1.6 on 2023-12-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_categories_course_subcategories_section_enrollment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='last_updated',
        ),
    ]
