# Generated by Django 4.1.6 on 2023-12-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_subcategories_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
