# Generated by Django 4.1.6 on 2024-01-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_order_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('cancel', 'cancel')], default='pending', max_length=20),
        ),
    ]
