# Generated by Django 4.1.6 on 2024-01-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_discount_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-id']},
        ),
    ]
